version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: 'cimg/node:17.5.0'
    environment:
      IMAGE_NAME: mayoct/cci-hippo-container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  
      - run:
          command: npm install     
      - node/install-packages
      - run:
          command: npm run test
      - run:
          name: Build a container
          command: docker build -t $IMAGE_NAME .

workflows:
  hippo_workflow:
    jobs:
      - build
