version: 2.1

orbs:
  node: circleci/node@5.0.0
  slack: circleci/slack@4.10.1

jobs:
  run_tests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Create package-lock.json
          command: npm install     
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1


workflows:
  hippo_workflow:
    jobs:
      - run_tests:
          context:
            - slack-secrets
