version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  run_tests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Create package-lock.json
          command: npm install     
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test


workflows:
  hippo_workflow:
    jobs:
      - run_tests
