version: 2.1

orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.3
  slack: circleci/slack@4.10.1
  snyk: snyk/snyk@1.2.3

jobs:
  build:
    docker:
      - image: 'cimg/node:17.5.0'
    environment:
      IMAGE_NAME: mfunaki/cci-hippo-container
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - node/install-packages
      - run:
          command: npm run test
      - docker/check
      - docker/build:
          lint-dockerfile: true
          image: $IMAGE_NAME
          tag: latest
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
          severity-threshold: critical
      - docker/push:
          image: $IMAGE_NAME
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  hippo_workflow:
    jobs:
      - build:
          context:
            - docker
            - slack-secrets
            - snyk-secrets
